### ISSUE TITLE
Move the Wallabag button at the top

### ISSUE THREAD

**Issue by romu70** [joshp23/ttrss-to-wallabag-v2#13]
When I want to save some article to read later, it's because I want to read it...later. So, it's strange to have the wallabag button at the bottom of the article, kind of you want to save it but already read it, you see?

Would be better to have the button at the top, even better make it available even if the article is not open, save it just by clicking the title line would be great.

**Comment by joshp23** [comment]
I can see why you might want the button up by the "publish" and "star" buttons, but I think that it would likely be more trouble than it is worth, to be honest. The button placement is a part of TTRSS core, and it makes sense to just hook into that rather than attempt to rewrite it. 

In combined mode ("Preferences" -> "Interface" -> "Combined Feed Display") with auto expand disabled ("Preferences" -> "Interface" -> "Automatically expand articles in combined mode")

![screenshot from 2017-01-04 12-45-06](https://cloud.githubusercontent.com/assets/7341917/21653377/c2f24cce-d27e-11e6-84ae-98d6a0465d37.png)


a click on a headline yields a preview, not the entire article. It works just fine with the button in its native location.

![screenshot from 2017-01-04 12-15-15](https://cloud.githubusercontent.com/assets/7341917/21651912/87b130f4-d278-11e6-999d-1980a4a941d0.png)

I think that "it would be better" in this case is pretty subjective, and depends on personal preference and individual workflow. If it is a huge issue, send me a pull request and try to include an option to place the button in either location and I'd be happy to try it out, otherwise this will be something that "might" get done if I get time.
