### ISSUE TITLE
Recent TinyTinyRSS update broke the plugin

### ISSUE THREAD

**Issue by ghost** [joshp23/ttrss-to-wallabag-v2#26]
I recently upgraded my TinyTinyRSS instance up to git version 8702ded and the ttrss-to-wallabag-v2 plugin no longer works.
There was a database update during the upgrade.
If there is anything else I can tell you then please ask me.
Thanks.

**Comment by joshp23** [comment]
Just re-enter your username and password into the plugin settings and see if that fixes the problem. I am working on this.

**Comment by joshp23** [comment]
If that works then please close this, as it is likely #23 and I will continue to address this there.

**Comment by joshp23** [comment]
update to the latest code, please. e68b0b7 added in a few debug data dumps, and checks for null auth tokens. This should fix your issue. If not, please re-open this.

**Comment by ghost** [comment]
Hi Josh , thanks for the work.
I removed the old plugin code and downloaded the latest.
Noted that 'oauth.php' is no longer included.
Disabled and re-enabled the plugin in TinyTinyRSS.
Checked my credentials in Wallabag , changed my password to be sure. Logged in a private session to make sure the new credentials are correct.
When I enter my username and password and press Save I get the following message -
'{"error":"invalid_client","error_description":"Client id was not found in the headers or body"}'                                                                                                             
Tried adding back the 'oauth.php' file , same result.

**Comment by joshp23** [comment]
Yes, the `oauth.php` code is now included in the `init.php` file, and so the additional file is totally unnecessary. This new code eliminates the saving of username and passwords in the tt-rss database, and is wholly OAuth token based, other than the first request.

It sounds like there may be an issue with your client ID. Are you certain the client id and secret are correctly entered and are identical to what is found in your Wallabag settings?

If you are feeling adventurous, you could delete the plugin storage for ttrss-to-wallabag for your user, and start fresh. This might be useful since you were running an older version of the plugin to begin with. 

Also, have a look in the `/path/to/ttrss/plugins.local/wallabag_v2/` folder. There should be a file in there called `debug.txt` which may have more information.

**Comment by ghost** [comment]
OK , my mistake , all working !
I thought I just needed to enter the server URL , username and password and that the Client ID and secret would be looked up.
After entering everything again and clicking Save it is all working.
Thank you so much for fixing it so quickly , I use it all the time!
Mark
