### ISSUE TITLE
 Error saving to Wallabag!: (0)

### ISSUE THREAD

**Issue by Aquan1412** [joshp23/ttrss-to-wallabag-v2#9]
Everytime when I save an article to Wallabag I get this error ( "Error saving to Wallabag!: (0)" ). However, the article is saved in my Wallabag. So I'm not sure if I'm missing something or if this is just a minor, although somewhat irritating bug.

During the setup of this plugin I followed all instructions.

**Comment by joshp23** [comment]
Running the current code, I am getting a success message from the plugin. 

An error on submit means that you are getting a (any)  _non-200_ code back from your wallabag server for some reason. In your case the script is returning a "0". This should be an indication of an empty response, ie, no data returned. But it could be a success response form ajax...

Here is what happens.

When the wallabag icon is clicked, the `postArticleToWallabag` function found in wallabag_v2.js is called via init.php. This can be seen on line 91 of init.php. 

This function in turn calls the `getwallabagInfo` function from init.php. This can be seen on line 8 of wallabag_v2.js

The status return code in question is called from curl on line 131 of init.php as a part of the `getwallabagInfo` function. That information is included in the data output array a little further down on line 143 of the same file, and this information (the data in the array) is passed along when `getwallabagInfo` is called by `postArticleToWallabag`. 

On line 18 of wallabag_v2.js, you can see where the status return code check is located. This is _supposed_ to reflect what the wallabag server tells us in response to our curl api call. 200 = success, and anything else get's returned on line 21.

So, you're not getting the 200 code back from wallabag for some reason. Could be curl, your wallabag server, or some info in your configuration.

I would use the plugin with dev-tools and see what the output is in console.

**Comment by 4oo4** [comment]
I'm also having this error, but my articles aren't saving and I can't quite figure out what's going on. I didn't get anything useful from the dev tools console, curl works fine for me, I have PHP-curl installed and working, and I verified that my Wallabag API is working correctly.

~~I appreciate you walking us through the code, I was wondering if you could show me how the `curl_init()` [function](https://github.com/joshp23/ttrss-to-wallabag-v2/blob/master/wallabag_v2/init.php#L117) in `init.php` would map to a curl request that you could make from the command line?~~

~~Because I'm only getting the 0 back as an error code instead of a true HTTP status code I'm thinking that this would be the best way to figure out what the error actually is, until the more detailed error messaging gets implemented.~~

Really excited to get this working! I also sent you a PR to fix a couple minor UI things.

EDIT: Looks like what I was looking for was [here](https://github.com/joshp23/ttrss-to-wallabag-v2/wiki), I'll have to do some messing around with that.

I'm thinking I might be missing something obvious, but maybe I overlooked it in the Wallabag API Docs. So, if my Wallabag base path is `example.com/wallabag/web` my URL for the plugin settings should be `https://example.com/wallabag/web`, and my Wallabag API client settings should also have `https://example.com/wallabag/web` as its Redirect URIs? I know for sure my API is working but I didn't see that mentioned explicitly in the docs.

**Comment by 4oo4** [comment]
I've been messing around with HTTPie and I'm still not getting anywhere. I suspected that it might be something to do with with my `X-XSS-Protection: 1; mode=block` http header I have set, but I tested this using by testing the API with `Referrer: https://example.com/tt-rss/index.php` and the API still worked (see below). Anywhere else I should be looking? Still getting nothing in the dev-tools console, nor in my web server logs.

```
http POST https://example.com/wallabag/web/api/entries.json \
>     "Authorization:Bearer REDACTED" \
>     url="https://www.theguardian.com/us-news/2016/jun/21/senate-bipartisan-gun-control-compromise-orlando" \
>     Referrer:https://example.com/tt-rss/index.php

HTTP/1.1 200 OK
0: application/json
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Wed, 22 Jun 2016 00:19:35 GMT
Public-Key-Pins: pin-sha256="REDACTED"; max-age=2592000
Server: nginx
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Dns-Prefetch-Control: content=on
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: noindex,noarchive,nofollow
X-XSS-Protection: 1; mode=block

{
    "_links": {
        "self": {
            "href": "/api/entries/29123"
        }
    }, 
    "content": "<meta itemprop=\"mainEntityOfPage\" content=\"http://www.theguardian.com/us-news/2016/jun/21/senate-bipartisan-gun-control-compromise-orlando\"/><div itemprop=\"publisher\" itemscope=\"\" itemtype=\"https://schema.org/Organization\">\n<meta itemprop=\"name\" content=\"The Guardian\"/><link itemprop=\"sameAs\" href=\"http://www.theguardian.com\"/></div><header 

### Snip article contents ###

it,” Rubio said.</p>\n<p>“But it has to be something that would have prevented the attack in Orlando or a future potential attack.”</p>\n</div>\n\n<div class=\"after-article js-after-article\"/>\n</div>\n\n</div>\n</div>\n", 
    "created_at": "2016-06-21T19:19:35-0500", 
    "domain_name": "www.theguardian.com", 
    "id": 29123, 
    "is_archived": 0, 
    "is_starred": 0, 
    "mimetype": "text/html", 
    "preview_picture": "https://i.guim.co.uk/img/media/6edf46f2649ce28d593763497e8c8271ca33ac66/0_123_3500_2099/3500.jpg?w=1200&h=632&q=55&auto=format&usm=12&fit=crop&bm=normal&ba=bottom%2Cleft&blend64=aHR0cHM6Ly91cGxvYWRzLmd1aW0uY28udWsvMjAxNi8wNi8wNy9vdmVybGF5LWxvZ28tMTIwMC05MF9vcHQucG5n&s=e59c8e2f9bd7b003aff2db6698d4aa6f", 
    "reading_time": 7, 
    "tags": [], 
    "title": "Senators unveil bipartisan proposal to tighten gun control laws after Orlando", 
    "updated_at": "2016-06-21T19:19:35-0500", 
    "url": "https://www.theguardian.com/us-news/2016/jun/21/senate-bipartisan-gun-control-compromise-orlando", 
    "user_email": "REDACTED", 
    "user_id": 3, 
    "user_name": "REDACTED"
}
```

**Comment by joshp23** [comment]
ok. in my setup, in wallabag the redirect url for the client is set to 

`"https:\/\/example.tt-rss.com\/prefs.php"`

and in tt-rss the wallabag url is set to

`https://example.wallabag.net`

The redirect url is meaningless in this case, afaik, but I never tested any other use case.

**Comment by 4oo4** [comment]
I've tried all of these tt-rss URLs for the redirect and still getting the same behavior:
```

**Comment by 4oo4** [comment]
I've tried all of these tt-rss URLs for the redirect and still getting the same behavior:

```
/prefs.php
/index.php
/backend.php
```

Could the fact that I'm not running wallabag on the root of my webserver be causing problems?

When I load TT-RSS with dev-tools, it gives me a handful of `PluginHost::run` warnings in the console, (`2,5,8,9`), but those are just on the page load for `index.php`, not in response to me using the Wallabag send link. I didn't know if those could be indicative of anything?

**Comment by 4oo4** [comment]
Reading through the Wallabag API docs more closely, it looks like I'm failing to receive something lik e this in my headers:
`Set-Cookie: PHPSESSID=bjie40ck72kp2pst3i71gf43a4; path=/; HttpOnly`

I'm thinking there's something I'm missing in my webserver config so that cookie with the session ID doesn't get passed properly?

EDIT: Fixed that by making sure that `session.auto_start = 1` was set in my `php.ini`, but still no luck.

**Comment by 4oo4** [comment]
~~OK, I think I may have found something. I started messing around with `backend.php` URLs to simulate how it's actually talking to Wallabag, and when I make a request to `https://example.com/tt-rss/backend.php?op=pluginhandler&plugin=wallabag_v2&method=getwallabagInfo&`, I get this JSON in response:~~

```
{"wallabag_url":"https:\/\/example.com\/wallabag\/web","wallabag_username":"REDACTED","wallabag_password":"REDACTED","wallabag_client_id":"REDACTED","wallabag_client_secret":"REDACTED","title":null,"status":0}
```

~~When I look at `wallabag_v2.js`, I see this function at [line 12](https://github.com/joshp23/ttrss-to-wallabag-v2/blob/master/wallabag_v2/wallabag_v2.js#L12) that parses the response, but I'm not seeing any place that it parses the `title` it gets back in response. I'm thinking that it's failing at this point because the request is not actually hitting wallabag (explaining why I didn't see it come through in the webserver logs). I just wanted to check and see if that function's supposed to ignore that part of the JSON, and if it can deal with the `null` thrown in there?~~

~~I'm really hoping it's that, or perhaps I'm using a version of Wallabag/TT-RSS that doesn't work with the plugin?~~

The function I was looking at seems to do something different, so I'm really not sure what to do at this point.

**Comment by joshp23** [comment]
I would investigate those errors on page load. They might have something to do with your plugin not functioning properly. If I understand this correctly, your articles are saving, but you are getting the "0" response. I had this issue, but the latest code should fix it... are you sure you have the latest version of the code from master?

**Comment by 4oo4** [comment]
I totally forgot about this for a while, sorry for the late reply. The articles actually aren't being saved when I get the error message, and the version I'm using is the commit from 6/22. To investigate the errors the PluginHostRun corresponds to what's in `errors.php` in tt-rss?

```
var ERRORS = [];
ERRORS[0] = "";
ERRORS[1] = "This program requires XmlHttpRequest to function properly. Your browser doesn't seem to support it.";
ERRORS[2] = "This program requires cookies to function properly. Your browser doesn't seem to support them.";
ERRORS[3] = "Backend sanity check failed.";
ERRORS[4] = "Frontend sanity check failed.";
ERRORS[5] = "Incorrect database schema version. &lt;a href='db-updater.php'&gt;Please update&lt;/a&gt;.";
ERRORS[6] = "Request not authorized.";
ERRORS[7] = "No operation to perform.";
ERRORS[8] = "Denied. Your access level is insufficient to access this page.";
ERRORS[9] = "Configuration check failed";
ERRORS[10] = "Your version of MySQL is not currently supported. Please see official site for more information.";
ERRORS[11] = "[This error is not returned by server]";
ERRORS[12] = "SQL escaping test failed, check your database and PHP configuration";
ERRORS[13] = "Method not found";
ERRORS[14] = "Plugin not found";
```

Because I'm getting several of them on page load, I'm not sure which ones I would want to look at. I also wasn't finding much in the tt-rss docs to elaborate on how one might resolve these errors.

**Comment by joshp23** [comment]
Those errors are beyond the scope of this plugin, for certain. 

But at first glance... you seem to be using an out of date browser, and _your database is out of date_ as well, you need to update it as the error log suggests... and you are not using a modern MySQL version, apparently... and on top of that, it appears as if you have some PHP configuration errors trying to happen, not sure. I would make sure error reporting is on for your vHost and for PHP, and set to debug, and comb through your logs.

Shared hosting perhaps?

**Comment by 4oo4** [comment]
No, I'm using PHP7 and mysql 5.7 on a dedicated server I built. I've been testing with the stable builds of Chromium/Firefox in Ubuntu.

Finally figured it out after all this time.  I needed `allow_url_fopen`  set to on for php, I had wanted to keep keep that off for security, but finally found a need for it. Thanks for the help!

**Comment by joshp23** [comment]
Holy cow, good find! I'll put that in the read me, thanks for posting back the solution.
